- go.mod
- parameter/parameter.go
- parameter/parameter_test.go
Add configuration to FetchConfig, whether config should be printed and in which file format the config should be loaded per default (YAML, JSON or TOML)
> adds config parameters to FetchConfig

- parameter/parameter.go
This PR adds the possibility to hide settings like passwords etc at "FetchConfig".
Standard print was changed to json again.
> Added ignoreSettingsAtPrint to FetchConfig

- database/badger_instance.go
- database/database.go
- database/interfaces.go
- Adds new functionality to the database interface (DeletePrefix + StreamReaders)
- Changes the database prefixes from a string to a single byte (less disk space)
- Add possibility to pass own badger instance to prefixDB
```diff
-func Get(name string) (Database, error) {
+func Get(dbPrefix byte, optionalBadger ...*badger.DB) (Database, error) {
```
> Database improvements

- iputils/iputils.go
Add the functionality to create a Union of IP addresses
> Add union to iputils

- lru_cache/lru_cache.go
This PR adds the possibility to delete a key from the LRU cache without the eviction call (needed for e.g. database pruning).
> Adds "DeleteWithoutEviction" to LRUCache

- network/managed_connection.go
- network/tcp/server.go
This PR adds traffic statistics to the `ManagedConnection` struct and fixes a possible deadlock in the `Close` event.
> Network cleanup

- node/node.go
Add `node.IsSkipped(plugin)` to check whether the given plugin is/will be skipped during load.
> Feat: Add public function to check wether a plugin is skipped

- objectstorage/cached_object.go
- objectstorage/events.go
- objectstorage/leak_detection.go
- objectstorage/object_storage.go
> Callback for eviction + Release(force)

- bytesfilter/bytesfilter.go
- bytesfilter/bytesfilter_test.go
- go.sum
Can for example be used to check if the bytes received via gossip have been seen before (threadsafe).
> Adds a new high performance bytes filter

- objectstorage/batch_writer.go
- objectstorage/object_storage.go
- objectstorage/test/objectstorage_test.go
- objectstorage/test/test_object.go
* Fixes the flush read lock never being unlocked within `accessCache`
* Made different functions for partitioned and unpartitioned cache access
* Rewrote some code to make it less loop based
* Added some comments to clarify what some functions do
> Refactors object storage

- objectstorage/object_storage.go
> Fix forEachCachedElementWithPrefix

- iputils/iputils.go
Adds the possibility to get all IP addresses from a host name (if it's an IP address it will check this IP address and returns this IP address as *IPAddresses)
> feat: Add GetIPAddressesFromHost

- objectstorage/object_storage.go
Fixes two problems with locks in object storage
> Fix locks in object storage

- objectstorage/object_storage.go
> Docs: added a comment

- objectstorage/object_storage.go
This PR exposes the LoadObjectFromBadger function.
> Expose LoadObjectFromBadger

- bytesfilter/bytesfilter.go
- database/database.go
- database/mapdb/mapdb.go
- filter/byte_array_filter.go
- objectstorage/leak_detection.go
- objectstorage/object_storage.go
- objectstorage/test/objectstorage_test.go
- objectstorage/test/test_object.go
This PR assures that the key over which we iterate is never used outside its validity.
> Fix Key usage

- objectstorage/object_storage.go
There could happen several race conditions due to the unprotected objectstorage size. Basically, for whatever operation such as delete and write, the objectstorage.size gets decremented/incremented. The problem arises while flushing, because there you try to read the objectstorage.size.
This is an example of a potential race condition in GoShimmer:
WARNING: DATA RACE
Read at 0x00c00008e0e0 by goroutine 11:
github.com/iotaledger/hive.go/objectstorage.(*ObjectStorage).flush()
/Users/angelo/go/pkg/mod/github.com/iotaledger/hive.go@v0.0.0-20200428004254-2aad9483e71c/objectstorage/object_storage.go:838 +0x75
github.com/iotaledger/hive.go/objectstorage.(*ObjectStorage).Shutdown()
/Users/angelo/go/pkg/mod/github.com/iotaledger/hive.go@v0.0.0- …
> Fix: Fixed a race condition during flush

- byteutils/xor_amd64.go
- byteutils/xor_amd64.s
- byteutils/xor_generic.go
- byteutils/xor_ppc64x.go
- byteutils/xor_ppc64x.s
- crypto/ed25519/seed.go
- crypto/ed25519/seed_test.go
To be able to implement a simple ed25519 based wallet, we need a way to deterministically derive keypairs from a seed.
> Feat: Added Seed to generate a deterministic sequence of KeyPairs

- autopeering/selection/events.go
- autopeering/selection/manager.go
This PR adds the `Distance` field to the PeeringEvent struct
> 📈 Add distance field to the peering event

- kvstore/mapdb/mapdb.go
- kvstore/mapdb/mapdb_test.go
- kvstore/mapdb/synced_map.go
- Use the same underlying map for all realms
- Add test cases
fixes #131
> Fix: Realm handling in MapDB

- objectstorage/batch_writer.go
- objectstorage/object_storage.go
Fixes https://github.com/iotaledger/hive.go/issues/154
> Fix: Fixed a deadlock

- websockethub/client.go
- websockethub/hub.go
Fixes race conditions in websockethub startup and shutdown.
Tested with hornet dashboard.
> Fix race conditions in websockethub startup and shutdown

- kvstore/mapdb/synced_map.go
This PR fixes a deadlock in the mapdb during iteration.
> Fix: fixes a deadlock in the mapdb

- byteutils/byteutils.go
- byteutils/byteutils_test.go
- kvstore/badger/badger.go
- kvstore/mapdb/mapdb.go
- kvstore/mapdb/synced_map.go
- objectstorage/batch_writer.go
- objectstorage/object_storage.go
- objectstorage/test/objectstorage_test.go
- objectstorage/test/test_object.go
- testutil/badgerdb.go
- testutil/tempdir.go
- typeutils/unsafe.go
Something weird is going on O_O
> Fix: Fixes a few bug (i.e. badger not being able to have set and delete commands in the same batch writer) + formatting issues + objectstorage bug

- marshalutil/marshalutil.uint16.go
added Uint16 marshalUtil support
> Feat: added Uint16 marshalUtil support

- datastructure/orderedmap/element.go
- datastructure/orderedmap/orderedmap.go
- datastructure/orderedmap/orderedmap_test.go
- datastructure/queue/queue.go
- datastructure/queue/queue_test.go
- datastructure/randommap/random_map.go
Moved existing datastructures from GoShimmer to hive.go.
> Move datastructures from GoShimmer to hive.go

- marshalutil/marshalutil.go
This PR adds a convenience method to the marshalUtil which allows us to marshal objects writing less code.
> Feat: Adds a Write method to the MarshalUtil

- objectstorage/cached_object.go
> Feat: added an accessor for the cachedobject key

- datastructure/walker/walker.go
This PR adds a utility data structure that enables the implementation of generic "Walkers" for goshimmer.
Example implementation of two walkers that can be used by several parts of the code:
```go
// WalkMessageID is a generic Tangle walker that executes a custom callback for every visited MessageID, starting from
// the given entry points. It accepts an optional boolean parameter which can be set to true if a Message should be
// visited more than once following different paths. The callback receives a Walker object as the last parameter which
// can be used to control the behavior of the walk similar to how a "Context" is used in some parts of the stdlib.
func (u *Utils) WalkMessageID(callback func(messageID MessageID, walker *walker.Walker), entryPoints MessageIDs, revisitElements …
```
> Add Generic Walker for Goshimmer

- timedqueue/timedqueue.go
This PR fixes a problem with the timedQueue that tries to modify the WaitGroup while another process is waiting.
> Fix: Fix a race condition in the timedQueue

- configuration/configuration.go
- configuration/configuration_test.go
- configuration/parser.go
This PR adds a method to store the current configuration to a file.
Added a test case.
> Add SaveFile method to store current configuration

- objectstorage/cached_object.go
- objectstorage/object_storage.go
This PR starts to refactor the object storage to use guard programming.
> Feat: Started rewriting objectstorage according to guard programming

- node/plugin.go
This PR adds loggin capabilities to the Plugin.
> Feat: added logging capabilities to the Plugin

- configuration/utils.go
- configuration/utils_test.go
> Feat: added string slice param support

- kvstore/rocksdb/rocksdb_instance.go
- kvstore/rocksdb/rocksdb_panic.go
This PR enables reading of internal rocksdb properties, like running compactions etc.
Tests still pass.
> Add Getters for rocksdb database properties

- marshalutil/marshalutil.float64.go
This PR adds the ability to marshal float64 values with the marshalUtil.
> Feat: added float64 value

- datastructure/thresholdmap/thresholdmap.go
- marshalutil/marshalutil.float64.go
Added the value of the found key to Floor and Ceiling.
> Added the value of the found key to Floor and Ceiling

- timedqueue/timedqueue.go
This PR fixes a potential deadlock in the TimedExecutor.
> Fix: Timedqueue deadlock

- events/thresholdevent.go
- events/thresholdevent_test.go
Moved ThresholdEvent to events package
- Enhancement / Refactor (a non-breaking change which adds functionality)
> Refactor: Moved ThresholdEvent to events package

- kvstore/mapdb/synced_map.go
This PR fixes a deadlock if the consumer of the syncedKVMap `iterateKeys` also accesses the KVStore.
> Fix deadlock in syncedKVMap iterateKeys

- objectstorage/object_storage.go
- objectstorage/partitions_manager.go
This PR adds a function `FreeMemory` to the object storage to re-create the internal maps, so that the GC can claim the free memory.
> Add function to free memory in object storage

- datastructure/orderedmap/orderedmap.go
> Feat: added new features to the orderedMap

- objectstorage/cached_object.go
- objectstorage/test/objectstorage_test.go
> Fix: the Transaction callback didnt release

- syncutils/multimutex.go
> Feat: Add interface to MultiMutex

- autopeering/discover/manager.go
This PR moves the `loadInitialPeers` into `start`. Previously, it was called in the constructor which lead to the master peers being pinged even when autopeering was disabled.
- Bug fix
> Fix: Do not load initial peers unless discovery is started

- workerpool/non_blocking_queued_workerpool.go
Adjust WP to be able to work with only 1 worker and respect order when polling from the queue.
- Enhancement
> Simplify non-blocking workerpool

- workerpool/non_blocking_queued_workerpool.go
- workerpool/non_blocking_queued_workerpool_test.go
Fixes shutdownlock and negative WG count
> QueuedWorkerPool fixes: shutdownlock and negative WG count

- platform/constants_freebsd.go
This PR adds the freebsd related plattform constants requested by #216
> Add plattform constants for freebsd

- autopeering/peer/peerdb.go
This PR flushes the updated seed to the peerdb. It fixes #303.
Please refer to #303 Reposteps.
> Flush newly generated seed to filesystem

- serializer/serializable.go
> add SerializableWithSize

- generics/objectstorage/cachedobject.go
- generics/objectstorage/cachedobject_test.go
- generics/objectstorage/objectstorage.go
- generics/objectstorage/storable_object.go
- generics/orderedmap/element.go
- generics/orderedmap/orderedmap.go
- generics/orderedmap/orderedmap_test.go
- generics/queue/queue.go
- generics/queue/queue_test.go
- generics/randommap/random_map.go
- generics/randommap/random_map_test.go
- generics/set/generic_set.go
- generics/set/set.go
- generics/set/simple_set_test.go
- generics/set/threadsafe_set_test.go
- generics/stack/generic_stack.go
- generics/stack/simple_stack_test.go
- generics/stack/stack.go
- generics/stack/threadsafe_stack_test.go
- generics/thresholdmap/thresholdmap.go
- generics/thresholdmap/thresholdmap_test.go
- generics/walker/walker.go
- go.mod
- go.sum
This PR implements generic wrappers for some implemented data structures. It also changes the required Go version to 1.18, which is currently in beta. 
Adapted and ran unit tests of wrapped data structures. 
> Generic data structures implementation

- generics/objectstorage/objectstorage.go
- generics/objectstorage/options.go
- generics/objectstorage/storable_object.go
- objectstorage/object_storage.go
- objectstorage/options.go
> Feat: added option for ObjectFactory

- daemon/daemon.go
`BackgroundWorker` are never cleaned up after they are finished.
This causes a memory leak.
This PR cleans up the worker from the daemon workerpool after the task is finished.
> Cleanup worker after they are finished

- syncutils/multimutex.go
- syncutils/multimutex_test.go
This PR improves and simplifies the multimutex and adds some more tests and benchmarks. 
> Improve multimutex

- .gitignore
- app/app.go
fix the outdated version message.
previous:
```
2022-05-18T12:39:44+01:00	INFO	App	Update to iotaledger available on https://github.com/wasp/0.2.5/releases/latest
```
fixed:
```
2022-05-18T12:43:49+01:00	INFO	App	Update to wasp 0.2.5 available on https://github.com/iotaledger/wasp/releases/latest
```
> Fix: versioncheck text

- serix/decode.go
- serix/encode.go
- serix/serix.go
This PR fixes race conditions in serix.ArrayRules.
> Fix array rules race condition

- datastructure/thresholdmap/thresholdmap.go
- identity/identity_test.go
Make threshold map thread safe
> Make thresholdmap thread-safe

- generics/shrinkingmap/shrinkingmap.go
- generics/shrinkingmap/shrinkingmap_test.go
This PR adds the possibility to define a count condition that triggers the shrinking of the map.
> Add count option to ShrinkingMap

- websockethub/hub.go
Returns the number of websocket clients
> Add Hub.Clients()

- generics/shrinkingmap/shrinkingmap.go
This PR adds two `ForEach` methods to the `ShrinkingMap`
> Add ForEach to ShrinkingMap

- app/utils/config/json.go
This adds a new line to the resulting config of the pretty printer.
Please delete options that are not relevant.
> fix: add newline at the end of config file

- core/identity/id.go
Add missing `FromBytes` method to `identity.ID`
> Decode ID from bytes

- apputils/parameter/parameter.go
- core/configuration/configuration.go
- core/generics/event/linkableevents.go
This PR adds the feature to use the pointer types in the reflection based config.
> Add pointer types to BindParameters

- core/serix/decode.go
- core/serix/map_decode.go
- core/serix/map_encode.go
- core/serix/map_encode_test.go
- core/serix/serix.go
Introduce interface allowing objects to serialize themselves into and from JSON format.
> Introduce (De)SerializableJSON interface

- core/serix/encode.go
- core/serix/serix.go
Use ArrayRules to validate length of collections based on tags, to be consistent with registered TypeSettings.
> Fix length validation using struct tags.

- core/serix/serix.go
> Fix: fixed serialization bug

- core/generics/constraints/constraints.go
- core/generics/constraints/serializable.go
- core/generics/constraints/types.go
- core/generics/kvstore/typedstore.go
- core/identity/id.go
> Simplify generics constraints

- core/kvstore/health_tracker.go
This PR is moving the package from hornet to hive.go
> Add StoreHealthTracker

- core/generics/constraints/constraints.go
- core/generics/onchangemap/onchangemap.go
- core/generics/onchangemap/onchangemap_test.go
- core/ioutils/ioutils.go
- core/objectstorage/options.go
This PR adds a map that executes a callback when the map changes or an item is modified.
> Add OnChangeMap

- core/bytesfilter/bytesfilter.go
- BytesFilter now using types.Identifier instead of stringifying bytes
- Also using a ShrinkingMap to avoid memory leaks
> BytesFilter improvements

- core/generics/model/storable.go
- Avoid serializing storable objects if they were deserialized from bytes by caching the bytes
- Also avoid re-serializing objects after they were serialized once by reusing the previously serialized bytes
> Avoid serializing storable objects if they were deserialized from bytes

- core/generics/model/immutable.go
- core/generics/model/interfaces.go
- core/generics/model/storable.go
> Make bytes caching optional

- core/generics/model/immutable.go
- core/generics/model/interfaces.go
- core/generics/model/mutable.go
- core/workerpool/unboundedworkerpool_test.go
Make bytes caching optional for all model types
> Make bytes caching optional for all model types

- core/app/app.go
Catches application panics and logs them.
As of now, application crashes won't be passed to the logger, this PR changes that.
using wasp
> pass app panics to the logger

- core/generics/model/immutable.go
- core/generics/model/mutable.go
- core/generics/model/storable.go
Fix data-race on cached model bytes.
> Fix data-race on cached model bytes.

- core/generics/model/immutable.go
- core/generics/model/mutable.go
> Fix models datarace

- core/autopeering/peer/peer.go
- core/autopeering/peer/peer_test.go
- core/autopeering/peer/peerdb.go
- core/autopeering/server/server.go
- core/crypto/ed25519/ed25519.go
- core/crypto/ed25519/private_key.go
- core/crypto/ed25519/private_key_test.go
- core/crypto/ed25519/public_key.go
- core/crypto/ed25519/public_key_test.go
- core/crypto/ed25519/seed.go
- core/crypto/ed25519/seed_test.go
- core/crypto/ed25519/signature.go
- core/crypto/ed25519/signature_test.go
- core/identity/id.go
- core/identity/identity_test.go
Also Fix the data race in Immutable
> Add error to the PublicKey Bytes() function

- core/database/engine.go
This prevents adding new database engines in the user code.
I need to add support for bolt db in my own app, so I want to remove this.
> Remove predefined allowed database engines

- app/daemon/daemon.go
- app/daemon/daemon_test.go
- autopeering/discover/manager.go
- autopeering/discover/mpeer.go
- autopeering/discover/protocol.go
- autopeering/selection/protocol.go
- core/logger/logger.go
- core/netutil/buffconn/buffconn.go
- core/network/managed_connection.go
- core/websockethub/client.go
- core/websockethub/hub.go
- kvstore/badger/badger.go
- kvstore/batch_collector.go
- kvstore/batch_writer.go
- kvstore/mapdb/mapdb.go
- kvstore/pebble/pebble.go
- kvstore/rocksdb/rocksdb.go
- kvstore/test/kvstore_test.go
- objectstorage/cached_object.go
- objectstorage/leak_detection.go
- objectstorage/object_storage.go
- objectstorage/storable_object_flags.go
- runtime/timeutil/ticker_test.go
- runtime/workerpool/workerpool_test.go
This PR updates the code to use the builtin atomic package (instead of the one by uber).
> Feat: Switched to builtin async package

- ds/ringbuffer/ringbuffer.go
- ds/ringbuffer/ringbuffer_test.go
This PR adds a simple, fixed capacity ring buffer that replaces elements in FIFO order.
> Ring buffer

- ds/advancedset/advancedset.go
This PR adds an Equals method to the AdvancedSet.
> Feat: Added Equals function to AdvancedSet

- ds/advancedset/advancedset.go
This PR reverts changes that introduced a duplicate Equals function.
> Feat: Reverted some changes

- runtime/valuenotifier/listener.go
In case someone does the following, the internal `deregister` could have been called twice, which is a problem if several listeners subscribe to the same value.
```go
listener := valuenotifier.Listener(value)
defer listener.Deregister()
listener.Wait(context.Background())
```
> Use `Deregister` to prevent calling `deregister` twice

- ds/orderedmap/orderedmap.go
Implement IsEmpty method and support nil receiver in other methods
> Implement IsEmpty method and support nil receiver in other methods

- ds/shrinkingmap/shrinkingmap.go
Add condition to Delete method of ShrinkingMap.
> Add condition to Delete method of ShrinkingMap

- ds/shrinkingmap/shrinkingmap.go
Implement Compute function on a ShrinkingMap
> Implement Compute function on a ShrinkingMap
