iotaledger/hive.go

- daemon/daemon.go
- daemon/daemon_test.go
* Adds the ability to define a shutdown priority when creating a new background worker
* One can create now separate instances of daemons for different purposes
* Adds a duration in `Shutdown()`/`ShutdownAndWait()` which is used to sleep between shutdowns of different priority background workers.
> Adds shutdown priority to daemon package

- daemon/ordered/daemon.go
- daemon/ordered/daemon_test.go
The shutdown order slice was not cleaned when a new background worker was defined with the same name, leading to `shutdown()` closing the same shutdown channel of a given worker N times the redefinition of the background worker.
> Fixes daemon shutdown() closing already closed shutdown channels

- daemon/ordered/daemon.go
This PR adds the possibility to mark the daemon as stopped, even before it was started.
If the daemon is already running, no new BackgroundWorkers can be started.
If the daemon was not running, it can't be started anymore.
This is necessary if the daemon received a shutdown() call during the startup process of HORNET.
Otherwise the BackgroundWorkers will never receive a shutdownSignal again.
> Add stopped signal to the ordered daemon

- batchworkerpool/batchworkerpool.go
- batchworkerpool/options.go
- workerpool/options.go
- workerpool/task.go
- workerpool/workerpool.go
- workerpool/workerpool_test.go
This PR adds a config option to the batched-/ workerpool to flush all tasks at shutdown signal.
It also removes the "sync barrier" from the workerpool since it is not used and broken.
> Added option to flush tasks at shutdown

- go.mod
- logger/config.go
- logger/events_test.go
- logger/logger.go
- logger/logger_test.go
The caller should deal with loading/providing the config:
- Have `InitGlobalLogger` that takes viper and fails on re-inint.
- `Named` panics when called un-initialized.
> Fix: Do not load logger config automatically

- logger/logger.go
Add function to create a logger without any config.
This logger is supposed to be used in tests or examples to get deterministic results without any additional config.
> Feat: Create simple deterministic logger for tests

- node/parameters.go
- `node.logLevel` no longer needed with new logger
- `node.disablePlugins` and `node.enablePlugins` should be string slices, as they can contain multiple values.
> Fix: Flags in node parameters

- iputils/iputils.go
* Adds an Alias field to `originAddress` (HORNET)
> feat: Add alias to originAddress

- backoff/backoff.go
- backoff/backoff_test.go
- backoff/example_test.go
- backoff/options.go
- backoff/options_test.go
Implements different  backoff policies for retrying operations that may fail:
- Zero backoff
- Constant backoff
- [Exponential backoff](https://en.wikipedia.org/wiki/Exponential_backoff)
All backoff policies can be further configured to
- limit retries
- jitter backoff
- cancel retires
- timeout retries
> Feat: Add simple and configurable backoff retry package

- go.mod
- go.sum
- objectstorage/batch_writer.go
- objectstorage/object_storage.go
- objectstorage/object_storage_options.go
- The `PersistenceEnabled` option does work now and skips the writes and loads from and to badger.
> Feat: Persistence in the ObjectStorage can be disabled

- objectstorage/batch_writer.go
- objectstorage/object_storage.go
- objectstorage/object_storage_options.go
- objectstorage/test/objectstorage_test.go
This PR adds a "Flush()" method to the objectstorage, which evicts all entries and waits until they are written to disk
> Feat: Adds a flush method 

- objectstorage/object_storage.go
- objectstorage/test/objectstorage_test.go
The ObjectStorage now has a "Shutdown()" method.
The Shutdown() method sets a flag to mark the storage as shutdown and then flushes and waits for all the elements to be persisted. Any additional calls to any of the public API methods will panic.
This allows us to test if an ObjectStorage is not being used anymore after the final shutdown (during debugging / development).
> Feat: Added a Shutdown() method to the ObjectStorage

- logger/events.go
When we create a ZAP core with events, we didn't specify a time.Duration encoder, which caused loggers to panic when they printed such value in a k/v log message.
> Fixes printing a message with a k/v structure to panic

- objectstorage/object_storage_options.go
- objectstorage/test/objectstorage_test.go
This PR renames `EnableLeakDetection` to `LeakDetectionEnabled` and adds a bool flag to enable it.
This way, we can define a setting in the config file and just pass the value of the config to this call, to enable the LeakDetection or not.
> Enable LeakDetection with bool parameter

- autopeering/discover/manager.go
- autopeering/discover/mpeer.go
- autopeering/discover/mpeer_test.go
* Add a `masters` mpeer list to record master peers
* Implement `wrapPeers` to initiate `masters`
* If a master peer is offline
1. set the `verifiedCount` to 0 => it will not be included in `GetVerifiedPeers`
2. move it to the front of active list => avoid reverifying the same offline node
> Fix: keep offline master peers in active peer list

- autopeering/discover/protocol.go
- autopeering/discover/protocol_test.go
- autopeering/peer/peerdb.go
- autopeering/peer/peerdb_test.go
- autopeering/selection/protocol.go
- autopeering/selection/protocol_test.go
Warning is issued when a peering request comes from a peer that is verified in the DB but not contained in the current list of verified peers.
- In this case, load the peer from the DB and consider peering. 
- If the peer is not verified, send a ping to assure that it will be verified soon.
- Handle the case where the address of the stored peer does not match the current address.
> Fix: "invalid stored peer" warning

- batchhasher/batch_hasher.go
- batchworkerpool/batchworkerpool.go
- workerpool/workerpool.go
- workerpool/workerpool_test.go
This adds the "added" flag to the "Submit" function in the workerpool and batchedworkerpool.
This way we know if the workerpool was shut down in the meantime (needed for proper cachedObject management).
> Add "added" flag to workerpool Submit calls

- node/plugin.go
- parameter/parameter.go
This PR allows to create Plugins without a callback. This makes sense, if the plugin does not execute anything in the configure step, but instead uses `init()` to execute its logic.
> Feat: Made run optional when creating a Plugin

- node/events.go
- node/node.go
- node/plugin.go
This phase can for example be used to trigger the parsing of the config file before the node runs checks on skipped Plugins.
It happens after ìnit()` and before `configure()`
> Feat: Added optional `Init` phase to plugin lifecycle

- node/node_options.go
Using assignment will only keep the plugins of the last NodeOption
in the list in newNodeOptions().
> Fix: Append plugins instead of assigning them in NodeOption

- objectstorage/batch_writer.go
- objectstorage/object_storage.go
- objectstorage/options.go
This PR adds an option `KeysOnly` to object storage to skip marshaling/unmarshaling and loading values from badger if the object has no data.
This should be much faster for objects that only consist of data of their keys.
> Add KeysOnly to object storage

- autopeering/discover/common.go
- autopeering/discover/manager.go
- autopeering/discover/protocol.go
- autopeering/discover/protocol_test.go
- autopeering/selection/common.go
- autopeering/selection/manager.go
- autopeering/selection/manager_test.go
- autopeering/selection/protocol.go
- autopeering/selection/protocol_test.go
- go.mod
This PR changes the autopeering VersionNum from `const` to `var` and allows to configure it via functional options. However, since the VersionNum is a global variable of the package, multiple autopeering instances will share the same version.
It also changes both discover and selection packages to accept functional options instead of a config struct
> Makes autopeering VersionNum configurable

- websockethub/client.go
- websockethub/hub.go
This PR adds a websocket manager called hub.
The hub has several advantages:
- maintains a list of active clients
- sends ping messages to all clients
- enables broadcast messages to all clients
- handles the concurrency of the websocket connections
> Add websockethub package

- objectstorage/batch_writer.go
- objectstorage/object_storage.go
- objectstorage/storable_object.go
- objectstorage/storable_object_factory.go
- objectstorage/test/objectstorage_test.go
- objectstorage/test/test_object.go
Initially, we tried to conform to the builtin MarshalBinary and UnmarshalBinary methods, but it does not make much sense, since SotrableObjects frequently store information in their keys. It therefore makes more sense to introduce custom methods that make it more clear that the unmarshaling happens in a 2 step process.
> Refactor: Renamed interface methods and signatures

- objectstorage/object_storage.go
- objectstorage/storable_object.go
- objectstorage/test/objectstorage_test.go
- objectstorage/test/test_object.go
This PR allows us to use the parsing methods of the object storage to read from a sequence of bytes.
> Refactor: Refactor the ObjectStorage parsing methods to return the consumed bytes

- objectstorage/object_storage.go
Object storage leaks if we want to delete a cachedObject that has no stored object.
We run database pruning in HORNET successfully after that change.
> Fix leak if cachedObject is empty

- .github/workflows/main.yml
Use reviewdog to run GoLangCI-Linter and report warnings as PR reviews. Replaces the discontinued GolangCI.com bot.
> Add reviewdog golangci-lint action

- objectstorage/object_storage.go
- objectstorage/test/objectstorage_test.go
This PR adds a function to iterate over all keys in the object storage.
> Add ForEachKeyOnly to object storage

- autopeering/selection/manager_test.go
- autopeering/server/server.go
Replace `*net.UDPConn` in the autopeering server with an interface only containing the required methods. This greatly simplifies tests and simulations as no full UDPConn is needed.
> Feat: Use interface for autopeering connection

- objectstorage/object_storage.go
This PR adds a function to delete a key directly from the persistence layer without accessing the object storage cache.
> Add DeleteEntryFromBadger

- objectstorage/object_storage.go
This PR adds a function to batch delete keys directly from the persistence layer without accessing the object storage cache.
> Add DeleteEntriesFromBadger

- autopeering/discover/events.go
- autopeering/discover/manager.go
- autopeering/discover/protocol.go
- autopeering/discover/protocol_test.go
- autopeering/selection/events.go
- autopeering/selection/manager.go
- autopeering/selection/manager_test.go
- autopeering/selection/protocol.go
Remove the global `Events` variable of the `autopeering` package and make it part of the `manager` struct.
> Remove global autopeering events

- logger/config.go
- logger/logger.go
- logger/logger_test.go
Viper.UnmarshalKey does not recognize a configuration group when defined with pflags therefore read logger config manually one by one
- Bug fix
> Load logger config from Viper one by one

- backoff/backoff_test.go
Make the `backoff` tests more robust by allowing 50ms of delay.
> Make backoff tests more robust

- daemon/daemon.go
- daemon/daemon_test.go
- syncutils/mutex.go
`shutdown()` locked the daemon and blocked reporting the running background processes, hence the node didn't have info on which processes are hanging.
This change introduces `RWMutex` instead of `Mutex` as lock in daemon. A read lock is used in 
`GetRunningBackGroundWorkers()`. `shutdown()` is separated into two stages (while preserving the original logic) so that they can use `Rlock()` and `Lock()` for shutting down workers and clearing the daemon respectively.
Ran with GoShimmer, shutdown is properly carried out. By manually inserting delays between shutting down the workers, the node reports which background workers are still running.
> Refactor daemon shutdown

- websockethub/client.go
- websockethub/hub.go
This PR adds the "dontDrop" variadic parameter to BroadcastMsg.
This way messages won't get lost if the client is too slow.
- [X My code follows the contribution guidelines for this project
> Add dontDrop to BroadcastMsg

- protocol/message/message.go
- protocol/message/message_test.go
- protocol/protocol.go
- protocol/protocol_test.go
- protocol/tlv/tlv.go
- protocol/tlv/tlv_test.go
A Type-Length-Value protocol for communicating over streaming protocols (tcp).
Before each actual packet, a `TLV Header` is inserted that denotes the type and length of the following packet. This way the receiver can correctly identify the start end end of a message.
`message.Registry` is used to initially register and provide available packet definitions. `message.NewRegistry()` takes a slice of message definitions and initializes the registry. Once this is done, the registry is immutable. Message definitions should be supplied to the function in a strictly monotonically increasing fashion according to their message type.
A `protocol` is instantiated with a `connection` and a `message registry`.
```go
conn, err := net.Dial("tcp", "goshimmer.org:80")
if err != nil {
// handle error
} …
```
> TLV Message Protocol

- objectstorage/object_storage.go
- objectstorage/test/objectstorage_test.go
##Description of change
- This fixes the optional prefix being ignored when iterating over keys when skipCache is set to true
- Added some more test cases covering this
> This fixes the optional prefix being ignored when iterating over keys when skipCache is set to true

- timeutil/ticker.go
Add a deferred `stop()` to assure that always all associated resources are released.
> Prevent timeutil.Ticker from leaking

- objectstorage/leak_detection.go
Leakdetection now shows not only the first consumer of a leak but also the current consumer that caused the detection to trigger.
This way it becomes much easier to determine the code part that caused the leak.
> Feat: Leakdetection shows more info

- kvstore/sequence.go
- kvstore/sequence_test.go
- Generate a sequence of integers backed by a key in the store
- Interval to prevent store updates on every query
- Do not generate index twice even after crash
> Add simple key-value store backed sequence

- node/node.go
- node/plugin.go
Refactor `node.plugins` from `map[string]int` to `map[string]*Plugin` so that we can use `plugin.isSkipped` in `/info` APIs `enabledPlugins` and `disabledPlugins`
See https://github.com/iotaledger/goshimmer/pull/449
> refactor node.plugins to expose *Plugin

- events/event.go
Not deferring the corresponding `Unlock` of a `Lock` can lead to nasty deadlocks when the attached closure panics.
> Defer the unlock in event package

- protocol/protocol.go
- `Read` must be locked to prevent issues with concurrent reads.
> Fix: Race condition in Protocol.Read

- objectstorage/object_storage.go
- objectstorage/test/objectstorage_test.go
StoreIfAbsent should only return true for a single caller of a set of concurrent callers that all try to store the same object.
I have added a unit test that checks if StoreIfAbsent really returns true once in a concurrent scenario.
> Fix: StoreIfAbsent should  be concurrency-safe

- parameter/parameter.go
- parameter/parameter_test.go
Adds an optional parameter to `LoadConfigFile` to skip parsing flags. This is useful if there are multiple invocations of `LoadConfigFile` since it currently causes `StringSlice` parameters to get duplicated by the amount of called `flag.Parse()`.
> Optionally skip parsing flags

- kvstore/mapdb/mapdb.go
- kvstore/mapdb/synced_map.go
- objectstorage/batch_writer.go
- objectstorage/cached_object.go
- objectstorage/object_storage.go
- objectstorage/options.go
- objectstorage/storable_object.go
- objectstorage/storable_object_flags.go
- objectstorage/test/objectstorage_test.go
This PR adds an option to ObjectStorage to persist objects directly to the persistence layer on creation of the object.
That can be used for objects that are never modified and should be stored immediately.
It also fixes a bug in the iteration of syncedKVMap.
Added a testcase to object storage.
> ObjectStorage "StoreOnCreation"

- bitmask/bitmask.go
- daemon/daemon.go
This PR changes the behavior of starting a new "BackgroundWorker".
If the daemon is already shutting down (waiting in "stopWorkers"), it doesn't wait to acquire the lock, but does an early return if the IsStopped flag is already set. This will prevent deadlocks on application level (like a shutdown deadlock in HORNET if a peer is handshaked and therefore starts a new BackgroundWorker exactly in the moment the shutdown signal is received.). Checking the IsStopped flag is thread safe because it is an atomicBool.
It also adds ModifyBit what got removed by Hans at refactoring for whatever reason.
Daemon tests still pass.
> Daemon early return

- websockethub/client.go
If someone tries to send a message to a client directly while hub is shutting down, it could panic.
> Do not send messages if websockethub was already shut down

- parameter/parameter.go
- parameter/parameter_test.go
Some people on discord, including me, have provided the file path with the extension during the Chrysalis part 1 tests on Comnet because it is normal to provide a full file path with extension and also comes up when trying to tab-auto-complete.
This PR allows config paths to optionally have the file extension.
E.g. 
```shell
$ ./hornet -c config_comnet.json
```
Providing just the file name without the extension is still perfectly fine after this change.
- Added a unit test for it
- Building Hornet and Goshimmer with this patch and manually testing configs with and without file extensions
> Allow providing config path with file extension

- parameter/parameter.go
- parameter/parameter_test.go
This PR changes the behavior of LoadConfigFile. Its a breaking change.
Instead of passing a bool value which indicates to bind all flags to the config, a FlagSet is passed now.
This allows to bind different flagsets to different config files.
To get the old behavior, just pass `nil` instead of `false` and `flag.CommandLine` instead of `true`
I added a testcase.
> Do not bind all CommandLine flags

- parameter/parameter.go
This PR fixes a bug in PrintConfig which lead to a panic.
If we wanted to hide a setting and it couldn't be found, the code paniced.
Tested in hornet.
> Fix panic if ignored setting doesn't exist

- datastructure/randommap/random_map.go
- datastructure/randommap/random_map_test.go
Next to the already existing `RandomEntry` method, that gets one random entry from the map, `RandomUniqueEntries` gets `n` number of unique entries. If n is bigger than the size of the map, all entries are returned.
Needed for refactored tip selection in GoShimmer.
> RandomUniqueEntries method for RandomMap

- daemon/daemon.go
- daemon/daemon_test.go
- daemon/interfaces.go
This PR adds a function to get a context that is done when the daemon is stopped to the daemon interface.
It can be used to determine if the node was shutdown.
I have seen this way to do that in go-libp2p.
Added a test case.
> Add ContextStopped to Daemon interface

- .github/workflows/test.yml
Previous versions of Go have an issue where a specially crafted input to a math operation can cause a panic ([CVE-2020-28362](https://security.archlinux.org/CVE-2020-28362)). This bug is fixed in Go 1.15.5.
- Chore
N/A
> chore: Use Go 1.15.5

- testutil/pebbledb.go
Add pebble DB in testutils that creates a temporary pebble DB for the GoShimmer unit test.
feature
> feat: Add pebbleDB testutils

- daemon/daemon.go
- daemon/interfaces.go
To be able to debug shutdown issues, this PR adds the ability to enable debug messages in the daemon. It is an optional feature and disabled by default.
> Feat: Add debugging features to the Daemon

- timeutil/ticker.go
- timeutil/ticker_test.go
Implemented new object oriented Ticker API for more flexible shutdown handling. Since we sometimes use Tickers in the Background workers of plugins and the workers can take a really long time to finish, we want to offer a way to wait only for the shutdown signal rather than the finishing of the job (i.e. when posting usage statistics to the metrics collecting server).
This speeds up the shutdown and prevents the server from being unnecessarily killed.
Old API:
```
// Always waits until the Ticker is shutdown and the last handler was fully executed
NewTicker(...)
```
New API:
```
// Doesn't wait but simply executes a background task that runs periodically.
ticker := NewTicker(...)
// Ticker can be manually shutdown instead of having to use a shutdown channel in the parameters. …
```
> Feat: Refactored ticker to support more flexible shutdown behavior

- kvstore/pebble/pebble.go
If you had a prefix which ended in byte 255 you were in for a lot of fun.
> Fixes prefix upper bound creation

- datastructure/randommap/random_map.go
Fixes a deadlock that happens when more unique entries are requested from `RandomMap` than it actually has.
> Fix deadlock in RandomMap

- autopeering/selection/manager.go
Currently a node iterates through a list of available peers, called filteredList, to identify peers that can be contacted for filling the outgoing neighbor list. If a peer rejects the node, the peer is added to a rejectionFilter. For a large enough salt life time (which is the case with the current settings) it is possible that the node has no more peers left in filteredList, thus stagnating with less than the maximum number of peers until its own salt is reset. With this change the node effectively resets the filteredList once it become empty. This can increase the communication overhead, but it is limited by the OutboundUpdateInterval.
- Enhancement 
The change in the autopeering module was tested only in an isolated simulation environment.
Add an `x` to the boxes that are relevant to …
> filteredList is allowed to loop when empty

- configuration/configuration.go
- configuration/configuration_test.go
This PR adds the possibility to ignore settings at storing of the config file.
Modified a test case.
> Add option to ignore settings at storing the config file

- objectstorage/object_storage.go
- timedexecutor/timedexecutor.go
Added a new ShutdownFlag for the TimedExecutor, that allows it to not wait for all Tasks to be completed before returning from the Shutdown method.
This is used i.e. by the objectStorage to prevent deadlocks.
> Fix: New ShutdownFlag for the TimedExecutor + deadlock fix

- objectstorage/cached_object.go
- objectstorage/options.go
This PR adds the option to the object storage, to pass a callback that is called if an object is evicted.
This can be useful in situations where you want to do a special action after no one needs this object anymore.
Tested if the callback is fired by using the option in hornet.
> Add OnEvictionCallback option to object storage

- configuration/utils.go
- configuration/utils_test.go
This PR adds a utility function to the configuration package that allows us to create, define and bind config variables by using the reflection API and tags of a struct holding the corresponding values.
> Feat: Added a method to Bind parameters to struct

- daemon/daemon.go
- daemon/daemon_test.go
To prevent accidental collisions in the BackgroundWorker naming due to i.e. copy and paste, we now always throw an error if a BackgroundWorker is created that uses a similar name as another BackgroundWorker.
> Fix: Avoid accidental BackgroundWorker collisions

- configuration/utils.go
- configuration/utils_test.go
When definining parameters using the BindParameters function then they only get bound to the CLI flags but do not reflect changes made by loading additional environment or config variables. This PR adds an UpdateBoundParameters function that makes changes in the config known to the parameters that are directly bound to variables.
> Feat: Feat: Add UpdateBoundParameters

- kvstore/badger/badger.go
- kvstore/bolt/bolt.go
- kvstore/debug/debug.go
- kvstore/kvstore.go
- kvstore/mapdb/mapdb.go
- kvstore/pebble/pebble.go
- kvstore/test/kvstore_test.go
- objectstorage/object_storage.go
- objectstorage/options.go
Added new debug KVStore that wraps a given KVStore and accepts an AccessCallback and CommandFilter. This can be used instead of adding the AccessCallback on all KVStore implementations
- The kvstore_test.go was executed with the new KVStore interface and all tests passed. The new store is not by default added to the kvstore_test.go dbImplementations to avoid spamming the test-log.
- [ x] My code follows the contribution guidelines for this project
- [ x] I have performed a self-review of my own code
- [x ] I have commented my code, particularly in hard-to-understand areas
- [ x] New and existing unit tests pass locally with my changes
> Removed AccessCallback from the KVStore interface and implementations.

- objectstorage/object_storage.go
- objectstorage/options.go
- objectstorage/test/objectstorage_test.go
This adds a ReadOption to the `Contains` call in object storage, so we can specify if we want to skip the cache or the storage.
The Iterator options had to be renamed.
Tests still pass.
> Add ReadOptions to object storage

- objectstorage/object_storage.go
- objectstorage/options.go
This PR adds an option to limit the maximum iterations in the object storage.
> Add WithIteratorMaxIterations option to object storage

- crypto/bls/bls_test.go
- crypto/bls/publickey.go
The use of BLS signature in Goshimmer transactions panics while unmarshalling transaction with BLS signature
- Bug fix
Added one unit test for BLS public key marshalling
- [x ] My code follows the contribution guidelines for this project
- [x ] I have added tests that prove my fix is effective or that my feature works
> fix bug in BLS public key unmarshalling

- timedqueue/timedqueue.go
This PR modifies the used syncronization mechanism for TimedQueues to fix a bug with negative WaitGroup counters and to make the logic simpler and work around possible deadlocks.
> Feat: Changed TimedQueue to use sync.Cond for waiting

- autopeering/peer/peer.go
- autopeering/peer/peer_test.go
- autopeering/peer/service/record.go
- crypto/ed25519/public_key.go
This PR adds JSON serialization/deserialization methods to `Peer` struct. The original need for this is the ability to manually pass neighbors to the gossip layer via JSON HTTP API or configuration file in Goshimmer, see https://github.com/iotaledger/goshimmer/pull/1191.
- Enhancement
The code is covered with unittests 
> Peer JSON serialization/deserialization

- events/event.go
Sometimes it is good to be able to trigger callbacks after a certain event has triggered (i.e. for debugging purposes in the tests). This PR adds an AttachAfter and an AttachBefore to every Event.
> Feat: Allow to attach callbacks to before and after triggering an Event

- events/closure.go
- events/event.go
The ID of the Closure was calculated using the pointer of the Closure object. This could lead to rare edge cases where two registered Callbacks received the same ID if the underlying Closure object was garbage collected in the mean time.
This PR fixes this problem by always assigning a new unique ID for every containing Closure.
> Feat: made Closure.ID unique

- crypto/ed25519/public_key.go
- crypto/ed25519/public_key_test.go
Now `PublicKey` marshals to JSON as base58 encoded string to be consistent with all other forms of representation.
Without that change the `PublicKey` was serializing to JSON as a list of integers for each byte from the key. 
Covered with unit tests
> Add JSON marshalling methods to PublicKey type

- kvstore/mapdb/mapdb.go
Batched db commit operation is supposed to be atomic, however during the commit external processes can read/write the backing database. This change locks db for reads/writes during the commit.
I ran all the test of Hive and they passed.
> Batched db commit operation should be atomic

- marshalutil/marshalutil.go
Allows clients to check whether we are done reading the bytes to be marshalled
Useful when the size is not known in advanced
In goshimmer it seems to work well. I am persisting several transactionIDs concatenated together and it works with no issues
> Add done reading function to marshalutil

- autopeering/selection/events.go
- autopeering/selection/manager.go
This PR adds the information about the peer to the autopeering DroppedEvent.
> Add peer to dropped event

- timedexecutor/timedexecutor.go
- timedqueue/timedqueue.go
- timedqueue/timedqueue_test.go
This PR adds the option to create a timed queue with a max size. In case a new element is added and the size would get bigger than allowed, the last element (furthest in the future) is deleted. 
Wrote a new unit test and make sure the old tests still pass.
> Add max size to the timed queue and timed executor

- go.mod
- go.sum
- node/events.go
- node/node.go
- node/node_test.go
- node/plugin.go
Makes it so that plugins can provide a struct of any type containing their dependencies (struct needs to embed `dig.In`) which gets populated before the plugin's configure callback is executed.
Plugins are supposed to `Provide` singletons etc. they provide by using the `*dig.Container` instance which can they acquire during the `Init` event. Check out the simple test to see how it works.
If the dependency graph can not be populated the `Node` panics.
> Adds dependency injection container to plugins

- node/node.go
Because the logger needs to be initialized by a plugin
> Use logger in node configure instead of init

- node/node_test.go
- node/plugin.go
As otherwise the phase callbacks could be mistakenly used as the deps struct.
> Re-order deps para

- events/queue.go
- events/queue_test.go
This PR adds an events.Queue that allows to queue Events for later execution. This is needed to delay the execution of events while some entities are locked.
> Feat: Added events.Queue

- marshalutil/marshalutil.go
Fix internal size value when initializing MarshalUtil with default buffer size.
- 
Ran unit tests of components using MarshalUtil (Goshimmer, reflection based serialization)
> Fix marshalutil with default size value.

- backoff/options.go
- backoff/options_test.go
- daemon/daemon.go
- daemon/daemon_test.go
- daemon/interfaces.go
- serializer/serializer.go
- timedqueue/timedqueue.go
- timeutil/sleep.go
- timeutil/ticker.go
- timeutil/ticker_test.go
- websockethub/client.go
- websockethub/hub.go
- workerpool/workerpool.go
This PR replaces most of the signal channels we used for cancellation or shutdown with contexts.
This is more go-idiomatic.
> Use contexts to cancel instead of signal channels

- autopeering/selection/manager.go
Reset rejectionFilter so that in the next call filteredList is full again. This should prevent nodes in small network to wait for the next salt update before having peers in the filteredList.
> Reset rejectionFilter

- configuration/configuration.go
Before checking the file extension, it should be checked if the file path exists.
> Fix config file exists check

- autopeering/selection/manager.go
- autopeering/selection/neighborhood_test.go
- autopeering/selection/selection_test.go
The PR fixes the response to autopeering inbound requests if the neighbourhood is already full.
> Fix inbound request status response

- identity/id.go
Adds an alias for identity.ID for easier debugging and development. 
Only affects the `String` method if an alias is registered which should only happen in tests anyway.
> Add identity.ID alias for easier debugging

- debuglogger/debuglogger.go
DebugLogger is a development and debug tool. It is a logger that supports log outputs with indentation to reflect the structure and hierarchical nature of executed functions and code blocks.
Extracted from https://github.com/iotaledger/goshimmer/pull/1770
> Add DebugLogger

- kvstore/batch_collector.go
- kvstore/batch_writer.go
- objectstorage/object_storage.go
This PR adds the possibility to flush the `BatchedWriter`.
Without that, it took the `ObjectStorage` a whole `BatchWriterTimeout` until the `ObjectStorage` flush was done, since it needed to wait until all objects were persisted by the `BatchedWriter`
> Add Flush function to BatchedWriter

- autopeering/peer/peerdb.go
- kvstore/badger/badger.go
- kvstore/batch_writer.go
- kvstore/bolt/bolt.go
- kvstore/debug/debug.go
- kvstore/kvstore.go
- kvstore/mapdb/mapdb.go
- kvstore/mapdb/mapdb_test.go
- kvstore/pebble/pebble.go
- kvstore/rocksdb/rocksdb.go
- kvstore/test/kvstore_test.go
- objectstorage/factory.go
- objectstorage/object_storage.go
- objectstorage/test/objectstorage_test.go
- testutil/badgerdb.go
- testutil/pebbledb.go
- testutil/rocksdb.go
This PR modifies the KVStore interface.
The unused Shutdown method was removed.
All interface functions also return an error parameter now.
A check for an already closed KVStore was added to every implementation as well as a test case for that.
> Add error returns to KVStore interface and remove Shutdown()

- debug/debug.go
- generics/event/event.go
- syncutils/starvingmutex.go
- syncutils/starvingmutex_test.go
- workerpool/blocking_queued_workerpool.go
- workerpool/blocking_queued_workerpool_test.go
Introduce getter and setter for the global debug.Enabled flag, preventing race conditions.
> Fix: debug.Enabled needs to be accessed atomically

- generics/event/event.go
- workerpool/blocking_queued_workerpool.go
- workerpool/blocking_queued_workerpool_test.go
Trigger all async tasks in a separate goroutine to avoid deadlock when all workers are processing tasks, that try to add new asynchronous tasks to the full task queue.
> Trigger all async tasks in a separate goroutine.

- serix/serix.go
- serix/serix_test.go
Allows the definition of min/max length for string and byte slice types using `minLen=x` and `maxLen=y` serix struct tag K/Vs.
> Adds minLen/maxLen serix tags

- core/go.mod
- core/go.sum
- core/serix/decode.go
- core/serix/encode.go
- core/serix/map_decode.go
- core/serix/map_encode.go
- core/serix/map_encode_test.go
- core/serix/numbers.go
- core/serix/serix.go
- core/serix/serix_test.go
Adds functions to de/encode objects to their map representation which can further be used for JSON de/encoding.
In order for the code to figure out which type is being decoded, during encoding, a `"type": <object code>` k/v is defined with the type's object type number.
Furthermore:
- Custom map keys can be defined via the `mapKey` serix field tag, otherwise the field name is used with having the first letter lower cased.
- Using `omitempty` a given value is omitted if it is its zero value.
- Slice/Array types which implement interfaces can declare their `mapKey` naming within `RegisterTypeSetting`. This allows for example for an array to implement an interface (such as say `Address`) but then having its map representation include a custom key to represent the array value (which is …
> Adds map/json de/encoding to serix

- core/app/app.go
For tools like gendoc, which is used to generate the documentation, it is important that the parameters are added in deterministic order.
> Fix non deterministic order of params in app module

- core/subscriptionmanager/subscription_manager.go
- core/subscriptionmanager/subscription_manager_test.go
This PR adds a subscriptions manager that tracks subscriptions to topics by clients.
If a client disconnects, all subscriptions are deleted.
Events are fired if no client subscribes to a specific topic anymore, or if the first client subscribes to one.
This can be useful if e.g. an INX subscription has to be created if the first client subscribes to a specific topic via MQTT or websocket.
> Add generic subscriptions manager

- core/subscriptionmanager/subscription_manager.go
Its better to fire the events without holding the lock of the subscription manager.
> Unlock mutexes before firing events

- core/app/app.go
- core/app/component.go
- core/daemon/daemon.go
- core/daemon/interfaces.go
- core/logger/config.go
The way the global logger is initialized now doesn't fit to the reflection based config parameters we use in the app module.
This PR removes the global logger from the app module, and initializes a root logger with parameters that are parsed with the reflection based logic.
> Use root logger in app instead of global logger

- core/configuration/configuration.go
This PR changes the behavior of the reflection based configuration.
Before the default value was always overwritten by the default value set in the tag.
Now it first checks if the actual value is zero, before it applies the default value from the tag.
This way we can overwrite default values.
Example:
```go
type ParametersPlugin struct {
Enabled bool `default:"true" usage:"whether the  plugin is enabled"`
}
var ParamsPlugin = &ParametersPlugin{
Enabled: false,
}
var params = &app.ComponentParams{
Params: map[string]any{
"plugin": ParamsPlugin,
},
Masked: nil,
}
```
Before `Enabled` was `true`, not it would be `false`.
> Fix configuration default values

- core/ioutils/ioutils.go
This PR changes the ioutil to use `MkDirAll` instead of `MkDir` so that subfolders are also created.
> Use MkDirAll to create subdirectories

- .golangci.yml
- core/database/engine.go
- core/database/utils.go
- core/subscriptionmanager/subscription_manager.go
This PR moves parts of the database package from hornet to hive.go.
It contains functions that can be used to check if the database folder matches the used database engine.
> Move database package from hornet to hive.go

- core/kvstore/flushkv/flushkv.go
- core/kvstore/flushkv/flushkv_test.go
- core/kvstore/kvstore.go
This PR adds a kvstore that wraps any other kvstore to flush changes immediately.
> Add a kvstore wrapper that flushes changes immediately

- core/timeutil/sleep.go
Using `time.After` creates a new timer which cannot be recovered by the garbage collector until it fires. This PR fixes this by assuring that `Timer.Stop` is always called.
> Fix: Potential memleak in timeutil.Sleep

- core/autopeering/discover/manager.go
- core/autopeering/selection/manager.go
- core/autopeering/server/server.go
- core/kvstore/batch_writer.go
- core/syncutils/starvingmutex.go
- core/timed/queue.go
- core/timeutil/sleep.go
- core/timeutil/timeutil.go
- core/workerpool/task.go
This PR fixes some potential memory leaks through the usage of `time.After` without cancelling when abort without the timer firing (see [here.](https://segmentfault.com/a/1190000040105436/en))
> Fix potential memory leaks through time.After

- core/generics/event/event.go
- core/generics/event/handler.go
- core/generics/event/loop.go
Add attach with worker pool functionality so that different components can attach with distinct worker pools. The standard `Attach` method still uses the global worker pool by default. Specific components can make use of this to lower contention on the global worker pool.
> Event.Attach with worker pool

- core/generics/model/storable.go
Add InvalidateBytesCache method to Storable to be able to invalidate the bytes cache after a Storable was modified but the bytes already calculated. For example, this happens on block creation: we need to compute the bytes to be able to create the signature. However, then we need to set the signature and subsequent serialization needs to take the modified Storable object, including signature into account.
> Add InvalidateBytesCache to Storable

- core/generics/shrinkingmap/shrinkingmap.go
Thir PR adds a convenience function for the ShrinkingMap, that allows to Pop the first element.
> Feat: added pop message to shrinkingmap

- core/generics/event/event.go
- core/generics/event/loop.go
- core/syncutils/counter.go
- core/timed/executor_test.go
- core/workerpool/group.go
- core/workerpool/group_test.go
- core/workerpool/unboundedworkerpool.go
- core/workerpool/unboundedworkerpool_test.go
This PR adds a workerpool.Group, which can act as an aggregator for a set of nested pools and groups.
> Feat: Added workerpool.Group

- app/components/shutdown/component.go
The shutdown handler was started in the configure stage.
All shutdown signals were ignored in the provide stage of the app, which lead to long running shutdowns if for example the NodeBridge tries to connect to a node in the provide stage, which is not available.
This PR changes the behaviour and starts the shutdown handler immediately.
> Catch shutdown signals during provide stage

- core/causalorder/causalorder.go
- core/causalorder/testframework_test.go
This PR introduces a callback to retrieve entity's parents, instead of always using `.Parents()`  method, as this is not flexible enough.
> Parents callback for CausalOrderer

- ds/advancedset/advancedset.go
- ds/advancedset/advancedset_test.go
This PR fixes a naming issue of the AdvancedSet constructor.
> Fix: Renamed constructor of AdvancedSet

- ds/advancedset/advancedset.go
This PR introduces the ability to call Slice() on an AdvancedSet that is nil.
> Feat: Add support for Slice() calls on nil AdvancedSets

- runtime/module/interface.go
- runtime/module/module.go
- runtime/module/provider.go
Move module package from GoShimmer to hive.go.
> Module is a trait that exposes a lifecycle related API, that can be used to create a modular architecture wheredifferent modules can listen and wait for each other to reach certain states.
> Module lifecycle traits

- ds/advancedset/advancedset.go
This PR allows to use the ForEach method of AdvancedSets that are "nil", without panicing.
> Feat: Allow use of nil AdvancedSet for iterations and membership checks

- ds/advancedset/advancedset.go
This PR adds a Range method to the AdvancedSet which allows to range over all elements without having to deal with possible errors.
```
mySet.Range(func(element T) {
doSth(element)
})
```
instead of:
```
_ = mySet.ForEach(func(element T) errror {
doSth(element)
return nil
})
```
> Feat: Add Range method to AdvancedSet (#504

- runtime/syncutils/mutex.go
- runtime/syncutils/mutex_deadlock.go
- runtime/syncutils/mutex_fake.go
- runtime/syncutils/rwmutexfake.go
FakeRWMutex can and should be used as a drop-in replacement for a regular mutex through the use of a `fakemutex` buildtag. Alternatively `deadlock` tag can be used to use a deadlock detection mutex. If neither tag is specified, a real `sync.Mutex/RWMutex` is used.
> Enable use of FakeRWMutex through a buildtag
